nxcdb: refactor shared database/workspace setup code & allow for creation/setting of workspaces outside of nxcdb interactive console
Pennyw0rth/NetExec pull request #123
Opened 2023-11-18 03:55 UTC by Marshall-Hallenbeck

- Refactors some database related code like creating the DB engine, creating workspaces, etc to be a single shared location
- Allows creation of workspaces via command line parameters in nxcdb
- Allows setting of active workspace in nxc config via command line parameters in nxcdb
- Remove redundant WS_PATH since there's already WORKSTATION_PATH in paths file

Now if you want to automate scanning, but have it in separate workspaces, and dont want to do some sed jankiness in the config, you can create a new workspace and make it the active one for NetExec with some command line calls.

2023-11-24 23:02 UTC, NeffIsBack requested changes
Rest looks good

2023-11-25 00:57 UTC, NeffIsBack commented
<img width="205" alt="image" src="https://github.com/Pennyw0rth/NetExec/assets/61382599/01282b3d-8e8b-4b80-953c-572d670530bb">

LGTM

2023-11-25 01:01 UTC, NeffIsBack commented on nxc/paths.py
> +
Resolved it

2023-11-25 01:09 UTC, NeffIsBack requested changes
<img width="807" alt="image" src="https://github.com/Pennyw0rth/NetExec/assets/61382599/d4a1ce78-8db2-41be-abcb-658b1840a537">

Ah one bug left. Now it tries to always create the default workspace on every command

2023-11-25 01:11 UTC, NeffIsBack commented
Added some other features:

- New command to list all existing workspaces and print out the current active workspace
- Change the workspace listing output to match git output style

2024-01-23 01:28 UTC, Marshall-Hallenbeck commented
Fixed the bug where it tries to create the default workspace every run. Ready for final review.

2024-02-12 18:25 UTC, NeffIsBack approved these changes
Working now, LGTM

2024-02-12 18:25 UTC, merged