add new security-questions module
Pennyw0rth/NetExec pull request #295
Opened 2024-05-08 22:19 UTC by Adamkadaban

this module will dump security questions and answers for all users on the machine assuming run as administrator

requires this PR to work: https://github.com/fortra/impacket/pull/1743

![image](https://github.com/Pennyw0rth/NetExec/assets/34610663/d7438c9d-8811-4ccc-bc85-4f452bfd9774)
example output shows `<Username> - <Question>: <Answer>` for each user

2024-05-10 18:54 UTC, Marshall-Hallenbeck commented
@Adamkadaban did you run Ruff against this? If you are using poetry: `poetry run python -m ruff check . --preview`

2024-05-10 19:22 UTC, Adamkadaban commented
> did you run Ruff against this? 

@Marshall-Hallenbeck Oh sorry, I didn't - but I have now. made the necessary changes and all checks are passing

2024-05-12 12:56 UTC, Dfte commented
Quick question but since these informations are dumped calling the SAMR RPC endpoint, can't we simply add this module in the code --sam option ?

2024-05-12 15:21 UTC, Adamkadaban commented
@Dfte I considered this too. I would say yes, but afaik `--sam` currently only tries to dump passwords in the same database. 
There are a ton of things we can dump with samr that currently aren't being dumped, so I assumed the best option would be a module

2024-05-15 20:01 UTC, mpgn commented on nxc/modules/security-questions.py
> +import json
`from json import loads` is a bit cleaner :)

2024-05-15 20:01 UTC, mpgn commented on nxc/modules/security-questions.py
> +                    resetData = json.loads(resetData)
`loads(resetData)`

2024-06-01 22:47 UTC, NeffIsBack requested changes
Not sure what is happening here, but when i swap out the `print()` for the exception logging this is the traceback:
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/faf6f778-944d-47bf-a3fd-980cfbcf73f2)

2024-06-01 22:47 UTC, NeffIsBack commented on nxc/modules/security-questions.py
> +            print(str(e))
Please use the logger with `.fail()` or `.error()` for error handling

2024-06-01 23:01 UTC, Adamkadaban commented
@NeffIsBack 
> Not sure what is happening here, but when i swap out the print() for the exception logging this is the traceback:

This looks like the ~very verbose~ logging that impacket provides when an information class doesn't exist. 

I think this means your impacket is outdated

2024-06-01 23:51 UTC, NeffIsBack commented
> @NeffIsBack 
> 
> > Not sure what is happening here, but when i swap out the print() for the exception logging this is the traceback:
> 
> 
> 
> This looks like the ~very verbose~ logging that impacket provides when an information class doesn't exist. 
> 
> 
> 
> I think this means your impacket is outdated

Oh yes, it's late, missed the fortra PR notice. Gonna update impacket and try again👍🏼

2024-06-02 11:01 UTC, NeffIsBack commented
Hmm okay so with impacket being updated i get an error on the dc and no output at all on the win11 machine. There should be a local account set up with sec questions.
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/3877fdd7-e6fb-425f-b712-00f620ef3791)
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/e9eb1ef1-55c2-4426-8be9-2ff9c0273a68)

The DC debug output:
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/daa172a6-74d6-45df-ab87-dde130d83afb)

The Win11 debug output (looks like its running fine, but doesn't find anything?):
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/90bc3cab-af3f-464e-85be-4ca5493650b1)

2024-06-18 15:08 UTC, Marshall-Hallenbeck requested changes
Code looks good, just requesting some variable renames so it's Python3-Pythonic.

2024-06-18 15:08 UTC, Marshall-Hallenbeck commented on nxc/modules/security-questions.py
> +        stringbinding = f"ncacn_np:{self.__targetIp}[\\pipe\\samr]"
This should be "string_binding"

2024-06-18 15:08 UTC, Marshall-Hallenbeck commented on nxc/modules/security-questions.py
> +        rpctransport = transport.DCERPCTransportFactory(stringbinding)
rename to "rpc_transport"

2024-06-18 15:08 UTC, Marshall-Hallenbeck commented on nxc/modules/security-questions.py
> +            serverHandle = resp["ServerHandle"]
rename to "server_handle"

2024-06-18 15:08 UTC, Marshall-Hallenbeck commented on nxc/modules/security-questions.py
> +            domainHandle = resp["DomainHandle"]
rename to "domain_handle"

2024-06-18 15:08 UTC, Marshall-Hallenbeck commented on nxc/modules/security-questions.py
> +            enumerationContext = 0
rename to "enumeration_context"

2024-06-18 15:08 UTC, Marshall-Hallenbeck commented on nxc/modules/security-questions.py
> +                    resetData = info["Buffer"]["Reset"]["ResetData"]
rename to "reset_data"

2024-07-18 22:28 UTC, NeffIsBack approved these changes
LGTM:
![image](https://github.com/user-attachments/assets/18e0397b-26fc-4e3f-a2ad-f82db6449bed)

Fyi, changed the loop from `break` to `continue` as we would otherwise stop if the first user doesn't have security questions.

2024-07-18 22:38 UTC, NeffIsBack commented
Looks like on DC this object doesn't have the UserResetInformation block. I added a try&Except block (with debug logging) just in case other servers have the same problem with some users.
![image](https://github.com/user-attachments/assets/4a9318c8-d74a-4e00-9f55-c14089fd5dc2)

2024-07-18 22:40 UTC, NeffIsBack approved these changes

2024-07-23 13:27 UTC, Marshall-Hallenbeck approved these changes

2024-07-23 18:24 UTC, merged