Refactor argparse options
Pennyw0rth/NetExec pull request #321
Opened 2024-05-21 19:44 UTC by Marshall-Hallenbeck

Allows us to pass in top level (universal) options ANYWHERE, meaning we can just append `--debug` to a command and it will work as intended.

Fixes some other parsing issues, like some argparse groups in SMB were named the same (not sure how that didn't cause issues), and a lot of the groups had nonsense names.

Adds a default option parser, so we do not have to include "Default: xyz" in the help information for options - it will automatically display those if they are not an empty string, None, False, etc.

2024-05-22 20:12 UTC, Marshall-Hallenbeck commented
Fixed conflicts with newly merged stuff (only big one was setting the retries to 10)

2024-05-22 21:05 UTC, Marshall-Hallenbeck commented
Updated to include the new DNS options, so you can put them at the end now :)

2024-05-23 15:17 UTC, mpgn submitted a review, later dismissed

2024-05-23 22:40 UTC, NeffIsBack requested changes

2024-05-23 22:40 UTC, NeffIsBack commented on nxc/protocols/smb/proto_args.py
>      smb_parser.add_argument("-H", "--hash", metavar="HASH", dest="hash", nargs="+", default=[], help="NTLM hash(es) or file(s) containing NTLM hashes")
Imo this belongs to the "Authentication" section

2024-05-23 22:40 UTC, NeffIsBack commented on nxc/protocols/smb/proto_args.py
>      dgroup.add_argument("--local-auth", action="store_true", help="authenticate locally to each target")
Same for this

2024-05-23 22:40 UTC, NeffIsBack commented on nxc/protocols/smb/proto_args.py
>      self_delegate_arg.make_required = [delegate_arg]
Same for this

2024-05-23 22:45 UTC, NeffIsBack commented
Functionality looking good so far
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/5e3b82f3-914c-4e8a-b53e-cb306d95b09d)

2024-05-23 23:08 UTC, NeffIsBack approved these changes
LGTM, should be working as intended

2024-05-24 01:08 UTC, NeffIsBack approved these changes

2024-05-24 01:13 UTC, merged