Smbghost scanning module
Pennyw0rth/NetExec pull request #407
Opened 2024-08-26 03:45 UTC by r4vanan

Module to scan for SMBGhost (CVE-2020-0796) Vulnerability
![image](https://github.com/user-attachments/assets/9ec55b95-e97c-449f-9962-e3e38753575b)

2024-08-26 22:48 UTC, NeffIsBack commented
Thanks for the PR! Cool one 🔥

2024-09-01 13:04 UTC, NeffIsBack requested changes
How did you test it? Is there any VM online available what i could download for testing?

2024-09-01 13:04 UTC, NeffIsBack commented on nxc/modules/smbghost.py
> +    sys.exit(2)
Looks like this isn't used and could be removed.

2024-09-01 14:54 UTC, r4vanan commented on nxc/modules/smbghost.py
> +    sys.exit(2)
that code is removed i will share vulnerable vm and share it to you. i test with vulnerable vm

2024-09-01 19:44 UTC, NeffIsBack commented on nxc/modules/smbghost.py
> +    sys.exit(2)
Thanks a lot!

2024-09-01 20:20 UTC, NeffIsBack approved these changes
LGTM
![image](https://github.com/user-attachments/assets/bd799941-f018-4c9c-9787-4cd9b507cee8)

2024-09-02 22:54 UTC, NeffIsBack approved these changes
LGTM

2024-09-02 23:19 UTC, merged