[POC ldap3
Pennyw0rth/NetExec pull request #412
Opened 2024-09-02 09:32 UTC by LightxR

2024-09-02 09:47 UTC, mpgn commented
The problem with ldap3 is that kerberos auth is not native, you need to manually install using apt or whatever `libkrb5-dev krb5-config` (it's not even default on kali).

2024-09-02 13:30 UTC, LightxR commented
I get your point but not sure to understand if it will be a problem for this PR : I only replace the impacket.ldap import and the code is still using impacket.krb5 so this should be OK.
I tested it on a fresh new debian VM without libkrb5-dev krb5-config packages and kerberos is working fine.
Let me know if I miss something

![image](https://github.com/user-attachments/assets/dfe9a0e0-9916-40d9-a762-6c3638794f3f)

2024-09-02 14:17 UTC, mpgn commented
> I get your point but not sure to understand if it will be a problem for this PR : I only replace the impacket.ldap import and the code is still using impacket.krb5 so this should be OK. I tested it on a fresh new debian VM without libkrb5-dev krb5-config packages and kerberos is working fine. Let me know if I miss something
> 
> ![image](https://private-user-images.githubusercontent.com/120841913/363704569-dfe9a0e0-9916-40d9-a762-6c3638794f3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODY3OTMsIm5iZiI6MTcyNTI4NjQ5MywicGF0aCI6Ii8xMjA4NDE5MTMvMzYzNzA0NTY5LWRmZTlhMGUwLTk5MTYtNDBkOS1hNzYyLTZjMzYzODc5NGYzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNDE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzI3YjZkZjY5NGIyODQwNWI2YTMwZTU0M2NlYjllMzQxNWEwOTVmODJhZTMxNDZhNDAzNjUzZmFhN2I0OGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cru7n-5LByQ3593au9MvXFKo43xnkfuEG8aM600D7hI)

Ok, i read the code a little bit to fast then, if this is working without any additional package this is an awesome PR !

2024-09-02 23:23 UTC, NeffIsBack commented
As you already wrote it into the title i converted the PR into a draft :)

2024-09-02 23:24 UTC, NeffIsBack commented
And of course thanks for the PR!
I will take a look at it when i got the time

2024-11-22 00:11 UTC, NeffIsBack requested changes
First of all thanks for the PR! This would be really cool to have!

There are many changes in the PR that seems to revert previous changes. Could it be that they were accidentally commited? 
With them in here it is nearly impossible to track what have been changed (and should have an impact on the new feature) and what not.

The same applies to the patch from the impacket ldap file. Currently i don't get a diff because the whole file is added. I think it would be best if we PR&merge it into the Pennyw0rth impacket fork so we can test it with this PR. Could you open up a PR to the fork?

When both changes are done i can review the PR and give proper feedback.

Fyi if you want to use a local version (or just some other repo) for impacket you can change that in the pyproject.toml file.
This is how you can use a local repo: 
```
[tool.poetry.dependencies]
my-package = { path = "../my/path" }
```

2024-11-22 13:35 UTC, NeffIsBack commented
@LightxR if you need help with git, hit me up on discord :)

2024-11-22 14:46 UTC, LightxR commented
I will update my PR and make modifications from the last netexec version.
I guess the changes you pointed out were committed after my PR was sent because I can't remember touching these parts of the code.
As suggested by mpgn on the discord, I will also update the PR format to match your last requirements :)

Regarding my code and more precisely the ldap section, the goal of the PR was to not use impacket.ldap anymore and to create a netexec ldap lib (based on ldap3) to handle ldap things. For the POC, I called it ldap3_patch (which is a bad name) just to search and replace ldap_impacket in the whole netexec code. Another approach could be taken, just let me know and I will update the PR in consequence.

As for git, I will ask you help for sure not to mess things up :D

2024-11-25 21:30 UTC, NeffIsBack commented
Thanks for the explaination!

However, i think maintaining a patched version of an ldap library inside of NetExec is neither the right place, nor feasible to maintain in the future. This should be strictly seperated, to avoid conflicts or the need to repatch the file every time something in impacket gets updated or patched. Is this only possible with ldap3 at the moment or is there a counterpart in impacket?

From my point of view we have two options how to handle this:
1. We implement the remaining features that are needed in impacket, using the ldap3 implementation as a guideline. This is probably the easiest way, because we would have to change NetExec only a little bit while providing the new feature to everyone who uses impacket.
2. We switch to ldap3. This would probably require most of the ldap protocol to be rewritten, including all of the dependent features like modules or flags. Though, ldap3 seems not that great maintained (the last commit was 8 months ago). That option is probably more work intensive :D 

My suggestion is, that we implement the features needed for cert auth and PR it. I can definitely help with that if i am needed

2024-11-26 14:49 UTC, mpgn commented
> We switch to ldap3. This would probably require most of the ldap protocol to be rewritten, including all of the dependent features like modules or flags. Though, ldap3 seems not that great maintained (the last commit was 8 months ago). That option is probably more work intensive :D

not compatible with kerberos by default so not the best option ;)

2024-11-26 14:51 UTC, mpgn commented
@LightxR in a perfect world where the pr in impacket is merged quickly, is it possible to directly update impacket ldap implementation ?

2024-11-27 13:13 UTC, LightxR commented
Right now the POC is quite dirty as you still need to provide username and domain to be able to use the pfx certificate but the ldap module is already "usable" as is (and kerberos is working fine^^), there are still work regarding the ldap3 implementation : laps flag and some modules (get-userPassword.py, get-desc-users.py, groupmembership.py, get-unixUserPassword.py) have not been modified and don't work in consequence.

I completely agree on the fact that working on impacket librairy is a more solid choice because the tool is currently stable with it and had a recent nice PR regarding channel binding :) 
No sure if I am not qualified to do the work on impacket but I will give it a try.

2024-12-18 23:02 UTC, lap1nou commented
Hey,

Nice PR idea @LightxR, I'm currently struggling to read gMSA password using Netexec on a server where LDAPS is not accessible and this PR would make this possible by using Start TLS I guess.

@NeffIsBack & @mpgn Would https://github.com/skelsec/msldap also be a candidate to replace Impacket LDAP maybe ?

Regards.

2024-12-19 08:36 UTC, mpgn commented
> Hey,
> 
> Nice PR idea @LightxR, I'm currently struggling to read gMSA password using Netexec on a server where LDAPS is not accessible and this PR would make this possible by using Start TLS I guess.
> 
> @NeffIsBack & @mpgn Would https://github.com/skelsec/msldap also be a candidate to replace Impacket LDAP maybe ?
> 
> Regards.

I have no problem to review and test the PR, but there is so many conflict with main branch that is starting to be archeology work :'(

2024-12-19 08:53 UTC, LightxR commented
Following the last conversation, I put on hold the work on ldap3 implementation and started looking for how it could be possible to add schannel support on impacket.ldap.

> > Hey,
> > Nice PR idea @LightxR, I'm currently struggling to read gMSA password using Netexec on a server where LDAPS is not accessible and this PR would make this possible by using Start TLS I guess.
> > @NeffIsBack & @mpgn Would https://github.com/skelsec/msldap also be a candidate to replace Impacket LDAP maybe ?
> > Regards.
> 
> I have no problem to review and test the PR, but there is so many conflict with main branch that is starting to be archeology work :'(

2025-05-28 14:14 UTC, closed without merging