Encode-decode subfolder for smb spider to avoid encode error in case non latin-1 symbols
Pennyw0rth/NetExec pull request #436
Opened 2024-10-05 08:25 UTC by a-urth

In case there is a folder with non latin-1 symbols (cyrillic lets say) smb spider will fail with following error
```
[17:00:56] ERROR    Exception while calling proto_flow() on target <ip-address>: 'latin-1' codec can't encode character '\u03b1' in position 60: ordinal not in range(256)                                          connection.py:174
```

Error itself comes from `impacket` which is used for smb connection during list directory step. Although its much easier (and faster) to fix it here.

In case characters are `latin-1` then no change to string will be done.

2024-10-05 17:34 UTC, NeffIsBack requested changes
Can you give me a setup i can test it with?
I tried to add the character you provided to the folder/filenames, but that didn't trigger the error.
At the moment the share content just disappears with the changes:
![image](https://github.com/user-attachments/assets/8acb7cc8-6c9e-40e0-8fa0-ec180b2be52b)

2024-10-07 08:27 UTC, a-urth commented
Interesting...
for me it happened with `--spider C\$ --spider-folder Users` and under `Users` there was `Администратор` folder, which caused the issue

2024-10-12 00:28 UTC, NeffIsBack commented
I might have found a solution:
![image](https://github.com/user-attachments/assets/56b2f5cf-f9f0-4c91-8f07-00f08e2c0f5d)

2024-10-12 00:35 UTC, NeffIsBack commented
@a-urth can you recheck if the error persists with #446 (or if this fixes it)?

2024-10-12 14:18 UTC, a-urth commented
Ah I see, then you was already on this issue, nice! let me try it asap and i'll get back to you

2024-11-12 22:03 UTC, NeffIsBack commented
@a-urth any updates? Everything working now?

2024-11-13 13:27 UTC, a-urth commented
@NeffIsBack yeah, sorry for delay. all good! thanks!

2024-11-13 13:28 UTC, closed without merging