Add raw-ntds-copy module
Pennyw0rth/NetExec pull request #468
Opened 2024-10-19 14:14 UTC by 0xb11a1

A new module for dumping the NTDS.dit, SYSTEM, and SAM files directly from the hard drive by analyzing the NTFS structure. This can be considered an alternative method to Shadow Copy, enabling the extraction of these files even if they are locked or protected by a process. It doesn't use the standard Windows API for file access, making it difficult for security solutions to detect which files are being copied.

<img width="1418" alt="image" src="https://github.com/user-attachments/assets/d9905d2a-0d15-48bb-8b67-939ec3ff2cd3">

2024-10-20 03:16 UTC, XiaoliChan commented
@0xb11a1 This is an awesome technique, any reference to this? I just know that [RawCopy](https://github.com/jschicht/RawCopy) can do this, but I don't know how to calculate the buf/offset stuff.

2024-10-20 10:18 UTC, 0xb11a1 commented
Hey @XiaoliChan, unfortunately I don’t have a specific reference for this as it’s a bit messy and gathered from multiple sources. However, this tool 'Active@ Disk Editor' has been really helpful, especially with its template feature that highlights header structures. here is an example of it :
![image](https://github.com/user-attachments/assets/ee576c3d-356d-4528-8b3a-46eee8ce4a9e)


What exactly do you mean by buf/offset? If you’re referring to the dataRun (the actual location of file fragments on disk), I understood it from this video: https://www.youtube.com/watch?v=6WFUM5eViIk . My implementation of it can be found in the 'decode_dataRun' function within the code. let me know if that helped or not.

2024-10-20 10:27 UTC, NeffIsBack commented
This looks really cool! Thanks for the PR.
Can you provide the source code for the base64 encoded code and how you compiled it, so i can verify the code myself?

2024-10-20 10:42 UTC, 0xb11a1 commented
Thanks @NeffIsBack, for decoding the code, it uses only base64, you can decode it directly yourself using Cyberchef from here https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)Decode_text('UTF-16LE%20(1200)')&oenc=65001 

What the code does is creating a function that reads "PHYSICALDRIVE0" by specific offset, then base64 the output binary and compress it using gzip for faster network transfer.

The decoded version :
 ```powershell
 Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;

public class CNativeMethods
{
    public const uint GENERIC_READ = 0x80000000;
    public const uint OPEN_EXISTING = 3;
    public const uint FILE_SHARE_READ = 0x00000001;
    public const uint FILE_SHARE_WRITE = 0x00000002;
    public const uint FILE_SHARE_DELETE = 0x00000004;

    [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
    public static extern SafeFileHandle CreateFile(
        string lpFileName, 
        uint dwDesiredAccess, 
        uint dwShareMode, 
        IntPtr lpSecurityAttributes, 
        uint dwCreationDisposition, 
        uint dwFlagsAndAttributes, 
        IntPtr hTemplateFile
    );

    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool ReadFile(
        SafeFileHandle hFile, 
        byte[] lpBuffer, 
        uint nNumberOfBytesToRead, 
        out uint lpNumberOfBytesRead, 
        IntPtr lpOverlapped
    );

    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool SetFilePointerEx(
        SafeFileHandle hFile, 
        long lDistanceToMove, 
        out long lpNewFilePointer, 
        uint dwMoveMethod
    );
}

public enum EMoveMethod : uint
{
    Begin = 0,
    Current = 1,
    End = 2
}
"@
Function read_disk{


$offset = [long]$args[0]
$size = [int]$args[1]
try {
    $handle = [CNativeMethods]::CreateFile("\\.\PHYSICALDRIVE0", 
        [CNativeMethods]::GENERIC_READ, 
        [CNativeMethods]::FILE_SHARE_READ -bor [CNativeMethods]::FILE_SHARE_WRITE -bor [CNativeMethods]::FILE_SHARE_DELETE, 
        [IntPtr]::Zero, [CNativeMethods]::OPEN_EXISTING, 0, [IntPtr]::Zero)

    if ($handle.IsInvalid) {
        throw "Failed to create file handle"
    }

    $moveToHigh = 0
    $success = [CNativeMethods]::SetFilePointerEx($handle, $offset, [ref]$moveToHigh, [EMoveMethod]::Begin)
    if (-not $success) {
        throw "Failed to set file pointer"
    }

    $buffer = New-Object byte[] $size
    $bytesRead = 0
    $success = [CNativeMethods]::ReadFile($handle, $buffer, $size, [ref]$bytesRead, [IntPtr]::Zero)

    if (-not $success) {
        throw "Failed to read file"
    }

    $memoryStream = New-Object System.IO.MemoryStream

    
    $gzipStream = New-Object System.IO.Compression.GzipStream($memoryStream, [System.IO.Compression.CompressionMode]::Compreass)

    $gzipStream.Write($buffer, 0, $buffer.Length)
    $gzipStream.Close()
    
    $compressedBytes = $memoryStream.ToArray()
    
    $compressedBase64 = [Convert]::ToBase64String($compressedBytes)

    Write-Output $compressedBase64

    

} catch {
    Write-Error "An error occurred: $_"
}

finally {
    if ($handle -and !$handle.IsInvalid) {
        $handle.Close()
    }
}
}

 ```

2024-10-20 11:20 UTC, Dfte commented
Is there a way to add this code as an option for the --ntds core option ? Since we already have --ntds vss, may be we can add --ntds raw ?

2024-10-20 11:30 UTC, mpgn commented
Can this technique create a bsod ?

2024-10-20 11:52 UTC, 0xb11a1 commented
@mpgn i don't think so as the main function that is being executed in the DC is "CreateFile" to read at specific offset, unless it has some weird edge case. i will do some more research into it and stress testing it. everything else is handled in python.

2024-10-21 10:27 UTC, 0xb11a1 commented
@Dfte, it is a good idea to do that, i tried to do it yesterday thought it will be quick. but since the module requires the `connection` class in order to execute the Powershell code on the target, not sure how to do it in the structure of NetExec, i need to look more into it.

2024-10-21 11:38 UTC, mpgn commented
> @Dfte, it is a good idea to do that, i tried to do it yesterday thought it will be quick. but since the module requires the `connection` class in order to execute the Powershell code on the target, not sure how to do it in the structure of NetExec, i need to look more into it.

self.conn.execute(...) ?

2024-10-21 11:52 UTC, Dfte commented
Stupid question of mine may be but there is no way you can get the offsets remotely without executing any powershell ? PhysicalDrive offsets are not stored in registry keys ? (may be something I can assist with ?)

2024-10-26 10:00 UTC, 0xb11a1 commented
@Dfte i don't think they are stored there, but if you find a way to get the offset from there i think it would be good to have it. But either way for the raw copy to happen i think we still need to execute a Powershell script in order to get the data based on the extracted offsets.

Also, i switch it to be an ntds option as @Dfte suggested: 
<img width="1419" alt="image" src="https://github.com/user-attachments/assets/2c35c979-61ba-4718-87ef-3bde26c06fe9">

2024-10-26 11:58 UTC, mpgn commented
You can also use impacket to read the result directly instead of letting the user enter manually the final command 😉

2024-10-26 13:03 UTC, 0xb11a1 commented
@mpgn  yea that is helpful, i will try to check some examples from Netexec and do the same.

2024-10-26 13:07 UTC, mpgn commented
> @mpgn yea that is helpful, i will try to check some examples from Netexec and do the same.

you can check this https://github.com/fortra/impacket/blob/835e17550b57606ee3c681ae1c3f0edea096ec19/examples/secretsdump.py#L317

2024-10-26 15:02 UTC, 0xb11a1 commented
@mpgn i've added it 

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/a0d9a3cd-84f3-47b4-9b25-a25bea65bdb3">

2024-12-16 21:26 UTC, mpgn commented
![image](https://github.com/user-attachments/assets/26e94a23-87f2-460a-a276-984cc8d1f1fe)

:crying_cat_face:

2024-12-18 12:40 UTC, 0xb11a1 commented
@mpgn  Also try changing the executing method `--exec-method smbexec` or to another one.

2024-12-18 23:02 UTC, NeffIsBack commented
From my testing it looks like it is working:
![image](https://github.com/user-attachments/assets/c8f23804-7adc-4f53-9f5b-ca834f9fbaaa)

@mpgn maybe AV killed some commands?

2024-12-20 20:31 UTC, mpgn commented
It's just two much, try running in debug mode it's just to much output 🥲

2025-03-24 16:12 UTC, NeffIsBack commented
@mpgn can you recheck this? Would nice if we could figure out the problem so we can merge the PR

2025-03-25 07:32 UTC, 0xb11a1 commented
I have updated the pull to sync with the main repo, making it work again. As for @mpgn , I was unable to reproduce the issue so far.

2025-07-10 21:59 UTC, NeffIsBack commented
Hi, @0xb11a1 really sorry for the extremely late response 👀 
We talked a bit internally and due to the required command execution i think it is best if we would convert it to a module similar to the `ntdsutil` module. Would that be fine for you?

2025-07-11 11:15 UTC, 0xb11a1 commented
Hey, no worries
will work on it during the weekend

2025-07-12 21:53 UTC, NeffIsBack commented
Great, thanks!

2025-07-14 22:44 UTC, NeffIsBack requested changes
Hi, it seems like there is a bit of stuff leftover from debugging that needs to be cleaned up.

In general, i opened the file and there were quite a lot of lines ruff complained about.
Please:
- Add more comments, so that it is clear what is done in each segment. For functions please use [docstrings](https://www.programiz.com/python-programming/docstrings)
- Either install ruff as a VSCode extension or run `poetry run ruff check . --preview` and fix the linting issues
- Only do meaningful debug/log statements and remove those which are leftovers from writing this module. Also make sure the debug statements are understandable so that it helps us figure out what is going wrong in case of crashes

2025-07-14 22:44 UTC, NeffIsBack commented on nxc/modules/raw-ntds-copy.py
> +            )
Please try to avoid multiline code if not necessary

2025-07-14 22:44 UTC, NeffIsBack commented on nxc/modules/raw-ntds-copy.py
> +        )
see above

2025-07-14 22:44 UTC, NeffIsBack commented on nxc/modules/raw-ntds-copy.py
> +                # self.logger.display(wanted_file_location)
see above

2025-07-14 22:44 UTC, NeffIsBack commented on nxc/modules/raw-ntds-copy.py
> +                self.logger.debug(f"{hex(curr_cluster_loc)=}")
Is this leftover from debugging?

2025-07-14 22:44 UTC, NeffIsBack commented on nxc/modules/raw-ntds-copy.py
> +                self.logger.debug(f"{size=}")
Is this leftover from debugging?

2025-07-14 22:44 UTC, NeffIsBack commented on nxc/modules/raw-ntds-copy.py
> +            self.logger.debug(f"{hex(dataRun[curr_datarun_indx])=}")
Not sure if i could get something out of this debug log. If you want to keep it please be a bit more precise what this is.

2025-07-14 22:46 UTC, NeffIsBack commented
Above I only marked a few examples of lines that need to be changed. Please review your code according to the stuff above

2025-07-19 09:54 UTC, 0xb11a1 commented
Did the requested changes, please review them and let me know if they are correct or if anything else needs to be done

2025-07-19 12:11 UTC, NeffIsBack commented
> Did the requested changes, please review them and let me know if they are correct or if anything else needs to be done

Looks much better! Thanks!

2025-07-19 16:59 UTC, NeffIsBack commented
Another thought, how about we name the module `ntds_dump_raw`? A bit more descriptive imo and if the module begins with `ntds...` it will be listed next to `ntdsutil` when listing modules. Thoughts everyone?

2025-07-19 18:02 UTC, 0xb11a1 commented
yea make sense

2025-07-20 11:36 UTC, NeffIsBack submitted a review, later dismissed

2025-07-20 18:00 UTC, NeffIsBack submitted a review, later dismissed
Also fixed the stuff for winrm. So now we can also dump the ntds.dit via winrm 🚀 

LGTM:
<img width="1233" height="737" alt="image" src="https://github.com/user-attachments/assets/3d01fcc3-b954-42de-b269-75d361abe53b" />

2025-07-20 18:08 UTC, 0xb11a1 commented
Nice addition, works on my end also
<img width="925" height="307" alt="image" src="https://github.com/user-attachments/assets/9dd607f0-cf31-4f54-963d-3a5056f71d60" />

2025-07-22 16:26 UTC, merged

2025-07-22 16:31 UTC, NeffIsBack commented
@0xb11a1 could you add documentation for the module to the [wiki](https://github.com/Pennyw0rth/NetExec-Wiki)? 

Also, just had in mind that we could also use this to dump SAM/LSA in general. If you want to continue working on it you could further improve the module by adding a "TARGET" (or something similar) option. Then you could select SAM/NTDS/LSA or a combination and the module would dump the respective files. For SAM this kind of already exists, but the module stops dumping the creds without the ntds.dit file:
<img width="1465" height="242" alt="image" src="https://github.com/user-attachments/assets/deab0c4c-f258-4b25-be72-89d0b932b72b" />
<img width="1371" height="225" alt="image" src="https://github.com/user-attachments/assets/562ea8e6-c42b-4cfa-9fb8-6a795f5fad7f" />

2025-07-22 16:33 UTC, NeffIsBack commented
Fyi, tried to implement it to the wmi protocol as well, but it crashes because the amount of returned data for one command is too large. The wmi protocol stores the output in a registry string value which has a [limit of ~16KB](https://learn.microsoft.com/en-us/windows/win32/sysinfo/registry-element-size-limits). We should probably fix that anyway.

2025-07-22 16:38 UTC, 0xb11a1 commented
We can manipulate the amount of retuned data easily as it stored in a variable, i set it up by default to 20mb
Will try to implement an exception for that

2025-07-23 12:00 UTC, NeffIsBack commented
> We can manipulate the amount of retuned data easily as it stored in a variable, i set it up by default to 20mb Will try to implement an exception for that

Imo every execution method should handle every amount of return data. Fixed it:
<img width="1524" height="734" alt="image" src="https://github.com/user-attachments/assets/9a7b808e-cff6-4613-b8fb-033e7603c78f" />

2025-07-23 12:05 UTC, 0xb11a1 commented
Nice, how long did it take to executed compared to smb ?

2025-07-23 12:54 UTC, NeffIsBack commented
> Nice, how long did it take to executed compared to smb ?

A lot more... I am currently on it to optimise the execution time, but it is a lot.

2025-07-23 17:27 UTC, 0xb11a1 commented
> @0xb11a1 could you add documentation for the module to the [wiki](https://github.com/Pennyw0rth/NetExec-Wiki)?
> 
> Also, just had in mind that we could also use this to dump SAM/LSA in general. If you want to continue working on it you could further improve the module by adding a "TARGET" (or something similar) option. Then you could select SAM/NTDS/LSA or a combination and the module would dump the respective files. For SAM this kind of already exists, but the module stops dumping the creds without the ntds.dit file: <img alt="image" width="1465" height="242" src="https://private-user-images.githubusercontent.com/61382599/469333135-deab0c4c-f258-4b25-be72-89d0b932b72b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMyNzQzODEsIm5iZiI6MTc1MzI3NDA4MSwicGF0aCI6Ii82MTM4MjU5OS80NjkzMzMxMzUtZGVhYjBjNGMtZjI1OC00YjI1LWJlNzItODlkMGI5MzJiNzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIzVDEyMzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTljODVlNmJhMjA5YThhNzNhNDdkNDRhYTU2Yzg3ZGI2NWYwY2UwZWZhZTZlNjkwODNlNDczNmE3NzYxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wyc7GfLrR491JhnXaqpmsiuPKtat3WGnHiNI706Y5Pk"> <img alt="image" width="1371" height="225" src="https://private-user-images.githubusercontent.com/61382599/469333284-562ea8e6-c42b-4cfa-9fb8-6a795f5fad7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMyNzQzODEsIm5iZiI6MTc1MzI3NDA4MSwicGF0aCI6Ii82MTM4MjU5OS80NjkzMzMyODQtNTYyZWE4ZTYtYzQyYi00Y2ZhLTlmYjgtNmE3OTVmNWZhZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIzVDEyMzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZjYyMjAwYzRmMjU5ODI3ZGNlNGI1YmI4ZjBmNzFjNTY0MGJjMWQ5Y2ZmYjc2MjljOTFiNmU0MDhlMjM3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vM2n1JgJj_D67m8vM5okG4j3qj3x9kRyayRdm3FXwU0">


yea we can do that, we can also make it even extract any file on the system.. that does require adding an addition MFT parsing to handle long file/folder names. 
i will start with the wiki documentation and the SAM/LSA, after that will move to make it accept any file path. what do you think ?

2025-07-23 22:10 UTC, NeffIsBack commented
> yea we can do that, we can also make it even extract any file on the system.. that does require adding an addition MFT parsing to handle long file/folder names. i will start with the wiki documentation and the SAM/LSA, after that will move to make it accept any file path. what do you think ?

I think being able to dump SAM/LSA/NTDS independently would be very nice. You could also add another option for arbitrary files, but this would only be a bonus for me.

2025-07-24 12:53 UTC, NeffIsBack commented
So SMB takes about 40s:
<img width="1538" height="812" alt="image" src="https://github.com/user-attachments/assets/569d64c0-314c-4a46-9638-6cca00403c1b" />

While WinRM needs about 156s:
<img width="1530" height="821" alt="image" src="https://github.com/user-attachments/assets/7ed9784e-a2ea-44e3-b247-130687324418" />

and WMI about 215s, not too bad imo:
<img width="1522" height="812" alt="image" src="https://github.com/user-attachments/assets/369cdcf4-97cb-4ca8-95ce-ffde183309e3" />

2025-07-24 13:26 UTC, 0xb11a1 commented
Added the LSA/SAM to none DC, not sure how to do it as option either by specifying the files directly or like this (having two mode "DC" and "PC"), any suggestion ? 
<img width="1373" height="555" alt="image" src="https://github.com/user-attachments/assets/fab3fb1a-7869-4f8a-885a-33f4e464cf6f" />

2025-07-24 13:29 UTC, NeffIsBack commented
> Added the LSA/SAM to none DC, not sure how to do it as option either by specifying the files directly or like this (having two mode "DC" and "PC"), any suggestion ? <img alt="image" width="1373" height="555" src="https://private-user-images.githubusercontent.com/32736765/470325015-fab3fb1a-7869-4f8a-885a-33f4e464cf6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzNjM5NjMsIm5iZiI6MTc1MzM2MzY2MywicGF0aCI6Ii8zMjczNjc2NS80NzAzMjUwMTUtZmFiM2ZiMWEtNzg2OS00ZjhhLTg4NWEtMzNmNGU0NjRjZjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI0VDEzMjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWUzZjhiZjgxZTQ1OGRkYTMwNDY1ZDdjZjQzNjI3N2NjMDczNjU2NzZlMTA4ODEyMmQwODZmYTJmMTE3ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.67pGGxM0jHvdS965AuLQZjtTPNhZgB-KdNH8C8mFZZo">

Nice! I would add an option called e.g. `TARGET` which can be filled with a combination of `SAM,LSA,NTDS`. Internally you can check if there is a comma in the string. If yes just split on this and extract each target, if not there is only one