Improve LDAP dc-list flag
Pennyw0rth/NetExec pull request #476
Opened 2024-10-28 14:18 UTC by termanix

---
name: Improved the dc-list.
about: In the previous code, it was working based on /etc/hosts and it would fail sometimes cause of that.
title: 'Improve LDAP dc-list flag'
labels: 'Enhancement, bug-fix'
assignees: ''

---
## Description

It was working base on /etc/hosts and tried to socket connection. It fails sometimes, espcially real life scenarios.
The functionality of the code was changed with direct DNS records and queries. It now works without being linked to /etc/hosts.
**Note**: It takes DNS nameserver IP address from self.host

And also used parse_result_attributes for parsing (https://github.com/Pennyw0rth/NetExec/pull/471)

## Type of change
Please delete options that are not relevant.
[+ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
NetExec ldap $IP -u username -p password --dc-list

## Screenshots (if appropriate):

![image](https://github.com/user-attachments/assets/b819b87b-a314-4d71-b85c-b53631a135f3)

2024-11-06 23:04 UTC, NeffIsBack requested changes
The connection object has a built-in dns resolver:
https://github.com/Pennyw0rth/NetExec/blob/72fee6af49ac48baba77cda16e6caeeedb2e7457/nxc/connection.py#L180-L191

This should probably be used, as this also respects the "new" dns flags

2024-12-31 09:03 UTC, mpgn commented
![image](https://github.com/user-attachments/assets/7e6e89b0-e4dc-4949-bcb7-ac13501851ed)

ok ✅

2024-12-31 09:03 UTC, mpgn approved these changes

2024-12-31 17:48 UTC, NeffIsBack requested changes
We already have dns args and imo these should be used here as well. So either the dns resolver should be the same as in the connection.py or the dns arguments should also be respected in this function

2024-12-31 17:48 UTC, NeffIsBack commented
Refering to:
https://github.com/Pennyw0rth/NetExec/blob/131e29e1179f2b99b37324dd8c6bb0c0de2c39ce/nxc/cli.py#L43-L47

2025-01-01 17:25 UTC, NeffIsBack approved these changes
LGTM:
![image](https://github.com/user-attachments/assets/7e33b672-fee2-455c-922f-0efc2a09c776)

2025-01-01 17:28 UTC, merged