New change-password module.
Pennyw0rth/NetExec pull request #512
Opened 2024-12-20 04:24 UTC by FaganAfandiyev

## Description

This new module is for changing the password of current user or a target user that is given as option. This is netexec implementation of impacket script changepasswd. No libraries are required except sys for exit.

## Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
I have tested this again a homelab and hackthebox DACL1 Attacks module for ForceChangePassword privilege. Had no issues with any of them. 

If you are using poetry, you can easily run tests via:
`poetry run python tests/e2e_tests.py -t $TARGET -u $USER -p $PASSWORD`
There are additional options like `--errors` to display ALL errors (some may not be failures), `--poetry` (output will include the poetry run prepended), `--line-num $START-$END $SINGLE` for only running a subset

## Screenshots (if appropriate):
![Leveraging ForceChangePassword.](https://github.com/user-attachments/assets/3f59f2fe-a26a-4982-a6d7-3f4e9ec9538e)

## Checklist:

- [ ] I have ran Ruff against my changes (via poetry: `poetry run python -m ruff check . --preview`, use `--fix` to automatically fix what it can)
- [ ] I have added or updated the tests/e2e_commands.txt file if necessary
- [ ] New and existing e2e tests pass locally with my changes
- [ ] My code follows the style guidelines of this project (should be covered by Ruff above)
- [ ] If reliant on third party dependencies, such as Impacket, dploot, lsassy, etc, I have linked the relevant PRs in those projects
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (PR here: https://github.com/Pennyw0rth/NetExec-Wiki)

Only thing left is to edit the wiki.

2024-12-20 07:14 UTC, termanix commented
Thanks for the PR and editting! I had such a module in mind too. But I think we can develop it in a more effective and versatile way. I think it would be much better if we add impacket's passwd tool, especially in cases of STATUS_PASSWORD_MUST_CHANGE and STATUS_PASSWORD_EXPIRED in SMB. I can help with this if you want.

2024-12-20 07:17 UTC, KriyosA commented
@termanix sure shoot me a dm on discord at @faganef . I'm also in netexec discord if you want to find me.

2024-12-20 07:28 UTC, termanix commented
Does [FaganAfandiyev](https://github.com/FaganAfandiyev) is your other account?

2024-12-20 07:30 UTC, FaganAfandiyev commented
Lol sorry just forgot to switch on mobile. The other account is for testing CICD attacks

2025-01-06 22:52 UTC, termanix commented
I'm not sure for smb.py for now but we'll see 😁

2025-01-06 23:32 UTC, FaganAfandiyev commented
Module is ready to be reviewed :)

2025-01-07 14:34 UTC, NeffIsBack commented
Thanks for the work! We'll review the PR when someone has the time to do so :)

2025-04-19 21:23 UTC, Marshall-Hallenbeck commented
@KriyosArcane can you add this module to the e2e tests?

2025-04-27 14:16 UTC, NeffIsBack requested changes
Very nice module!
So far, changing the password with a `NEWPASS` works flawlessly, just changing the `NTHASH` does not work for me:
![image](https://github.com/user-attachments/assets/5723609d-b5cf-40ca-bdb1-ef996a5b2f0d)

As @Marshall-Hallenbeck already mentioned, please also add the e2e tests, see:
https://github.com/Pennyw0rth/NetExec/blob/main/tests/e2e_commands.txt

2025-04-27 14:16 UTC, NeffIsBack commented on nxc/modules/change-password.py
> +            netexec smb <DC_IP> -u username -H oldnthash -M change-password -o OLDNTHASH='oldnthash' NEWPASS='newpass'
`OLDPASS`/`OLDNTHASH` can probably be used from connection.nthash/connection.password

2025-04-27 14:16 UTC, NeffIsBack commented on nxc/modules/change-password.py
> +            self.context.log.success(f"Successfully changed password for {target_username}")
This somehow throws an internal error that it can't get the underlying smb connection. Not sure why and how this is happening, but changing the NT hash does not work for me as of now:
![image](https://github.com/user-attachments/assets/7d51a346-98e4-4607-b990-3ee51bf9b173)

2025-04-28 22:35 UTC, KriyosArcane commented on nxc/modules/change-password.py
> +            netexec smb <DC_IP> -u username -H oldnthash -M change-password -o OLDNTHASH='oldnthash' NEWPASS='newpass'
I was not aware of it being available in connection.nthash. I will soon push an update using this after I test it

2025-04-28 22:53 UTC, KriyosArcane commented on nxc/modules/change-password.py
> +            netexec smb <DC_IP> -u username -H oldnthash -M change-password -o OLDNTHASH='oldnthash' NEWPASS='newpass'
```suggestion
        # If OLDPASS or OLDHASH are not specified, default to the credentials used for authentication.
        if not self.oldpass:
            self.oldpass = connection.password
        if not self.oldhash:
            self.oldhash = connection.nthash
```

Those values are set using connection.nthash if not provided but it is required to provide a different user's old password to reset the password. That option is left for that reason

2025-05-01 20:32 UTC, NeffIsBack commented on nxc/modules/change-password.py
> +            self.context.log.success(f"Successfully changed password for {target_username}")
That is the debug log:
```py
[16:31:12] DEBUG    NXC VERSION: 1.4.0 - SmoothOperator - 61277c88 - 9                                                                                                                                                                                                                                                                                                                             cli.py:28
           DEBUG    PYTHON VERSION: 3.13.2 (main, Mar 13 2025, 14:29:07) [GCC 14.2.0]                                                                                                                                                                                                                                                                                                          netexec.py:81
           DEBUG    RUNNING ON: Linux Release: 6.12.20-amd64                                                                                                                                                                                                                                                                                                                                   netexec.py:82
           DEBUG    Passed args: Namespace(version=False, threads=256, timeout=None, jitter=None, verbose=False, debug=True, no_progress=False, log=None, force_ipv6=False, dns_server=None, dns_tcp=False, dns_timeout=3, protocol='smb', target=['192.168.56.11'], username=['pw_expired'], password=[], cred_id=[], ignore_pw_decoding=False, no_bruteforce=False,                          netexec.py:83
                    continue_on_success=False, gfail_limit=None, ufail_limit=None, fail_limit=None, kerberos=False, use_kcache=False, aesKey=None, kdcHost=None, pfx_cert=None, pfx_base64=None, pfx_pass=None, pem_cert=None, pem_key=None, server='https', server_host='0.0.0.0', server_port=None, connectback_host=None, module=['change-password'],                                                    
                    module_options=['OLDNTHASH=72e9fdb99a29a7902e644ec75ad88806', 'NEWNTHASH=4f622f4cd4284a887228940e2ff4e709'], list_modules=False, show_module_options=False, hash=['72e9fdb99a29a7902e644ec75ad88806'], delegate=None, no_s4u2proxy=False, domain=None, local_auth=False, port=445, share='C$', smb_server_port=445, no_smbv1=False, gen_relay_list=None, smb_timeout=2,                 
                    laps=None, generate_hosts_file=None, generate_krb5_file=None, sam=None, lsa=None, ntds=None, dpapi=None, sccm=None, mkfile=None, pvk=None, enabled=False, userntds=None, shares=False, dir=None, interfaces=False, no_write_check=False, filter_shares=None, smb_sessions=False, disks=False, loggedon_users_filter=None, loggedon_users=None, users=None,                              
                    users_export=None, groups=None, computers=None, local_groups=None, pass_pol=False, rid_brute=None, qwinsta=False, tasklist=False, wmi=None, wmi_namespace='root\\cimv2', spider=None, spider_folder='.', content=False, exclude_dirs='', depth=None, only_files=False, pattern=None, regex=None, put_file=None, get_file=None, append_host=False, exec_method='wmiexec',                
                    dcom_timeout=5, get_output_tries=100, codec='utf-8', no_output=False, execute=None, ps_execute=None, obfs=False, amsi_bypass=None, clear_obfscripts=False, force_ps32=False, no_encode=False)                                                                                                                                                                                           
           DEBUG    Protocol: smb                                                                                                                                                                                                                                                                                                                                                             netexec.py:137
           DEBUG    Protocol Path: /home/kali/Git/NetExec/nxc/protocols/smb.py                                                                                                                                                                                                                                                                                                                netexec.py:140
           DEBUG    Protocol DB Path: /home/kali/Git/NetExec/nxc/protocols/smb/database.py                                                                                                                                                                                                                                                                                                    netexec.py:142
           DEBUG    symmetric using "pyCryptodomex" for "DES"                                                                                                                                                                                                                                                                                                                                 __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "TDES"                                                                                                                                                                                                                                                                                                                                __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "AES"                                                                                                                                                                                                                                                                                                                                 __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "RC4"                                                                                                                                                                                                                                                                                                                                 __init__.py:55
           DEBUG    Protocol Object: <class 'protocol.smb'>, type: <class 'type'>                                                                                                                                                                                                                                                                                                             netexec.py:145
           DEBUG    Protocol DB Object: <class 'protocol.database'>                                                                                                                                                                                                                                                                                                                           netexec.py:147
           DEBUG    DB Path: /home/kali/.nxc/workspaces/default/smb.db                                                                                                                                                                                                                                                                                                                        netexec.py:150
[16:31:13] DEBUG    Modules to be Loaded for sanity check: ['change-password'], <class 'list'>                                                                                                                                                                                                                                                                                                netexec.py:182
           DEBUG    Loading mod [...]

2025-05-01 20:33 UTC, NeffIsBack commented on nxc/modules/change-password.py
> +            self.context.log.success(f"Successfully changed password for {target_username}")
And here is a stacktrace of the error, it fails because somehow the rpc connection does not have an smb_connection:
```py
└─$ poetry run nxc smb 192.168.56.11 -u pw_expired -H 72e9fdb99a29a7902e644ec75ad88806 -M change-password -o OLDNTHASH=72e9fdb99a29a7902e644ec75ad88806 NEWNTHASH=4f622f4cd4284a887228940e2ff4e709  
SMB         192.168.56.11   445    WINTERFELL       [*] Windows 10 / Server 2019 Build 17763 x64 (name:WINTERFELL) (domain:north.sevenkingdoms.local) (signing:True) (SMBv1:False) 
SMB         192.168.56.11   445    WINTERFELL       [-] north.sevenkingdoms.local\pw_expired:72e9fdb99a29a7902e644ec75ad88806 STATUS_PASSWORD_MUST_CHANGE 
[16:32:22] ERROR    AttributeError: 'TCPTransport' object has no attribute 'get_smb_connection'                                                                                                     
                    ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most 
                    │ /home/kali/Git/NetExec/nxc/modules/change-password.py:146 in _smb_samr_change                                                                                                 
                    │                                                                                                                                                                               
                    │   143 │   │   │   │   │   context.log.success(f"Successfully changed password for                                                                                             
                    │       {target_username}")                                                                                                                                                     
                    │   144 │   │   │   else:                                                                                                                                                       
                    │   145 │   │   │   │   # Handle anonymous/null session password change                                                                                                         
                    │ ❱ 146 │   │   │   │   self.mustchangePassword(target_username, target_domain, self.oldpass,                                                                                   
                    │       newPassword, "", oldHash, "", newHash)                                                                                                                                  
                    │   147 │   │   except AttributeError as e:                                                                                                                                     
                    │   148 │   │   │   context.log.exception(f"AttributeError: {e}")                                                                                                               
                    │   149 │   │   │   context.log.fail("SMB-SAMR password change failed: Ensure that either the                                                                                   
                    │       OLDPASS or OLDNTHASH option is provided and attempt again.")                                                                                                            
                    │                                                                                                                                                                               
                    │ /home/kali/Git/NetExec/nxc/modules/change-password.py:166 in mustchangePassword                                                                                               
                    │                                                                                                                                                                               
                    │   163 │   │   │   self.context.log.success(f"Successfully changed password for                                                                                                
                    │       {target_username}")                                                                                                                                                     
                    │   164 │   │   else:                                                                                                                                                           
                    │   165 │   │   │   # Use NT internal function to set new password or hash                                                                                                      
                    │ ❱ 166 │   │   │   samr.hSamrSetNTInternal1(self.dce, target_username, newPassword,                                                                                            
                    │       newPwdHashNT)                                                                                                                                                           
                    │   167 │   │   │   self.context.log.success(f"Successfully changed password for                                                                                                
                    │       {target_username}")                                                                                                                                                     
                    │   168                                                                                                                                                                         
                    │                                                                                                                                                                               
                    │ /home/kali/.cache/pypoetry/virtualenvs/netexec-RzaU0oFN-py3.13/lib/python3.13/site-packages/impacket/dcerpc/v5/samr.py:2994 in hSamrSetNTInternal1                            
                    │                                                                                                                                                                               
                    │   2991 │   │   except:                                                                                                                                                        
                    │   2992 │   │   │   pass                                                                                                                                                       
                    │   2993 │                                                                                                                                                                      
                    │ ❱ 2994 │   session_key = dce.get_rpc_transport().get_smb_connection().getSessionKey()                                                                                         
                    │   2995 │                                                                                                                                                                      
                    │   2996 │   request['Buffer']['Internal1']['EncryptedNtOwfPassword'] =                                                                                                         
                    │        crypto.SamEncryptNTLMHash(hashNT, session_key)                                                                                                                         
                    │   2997 │   request['Buffer']['Internal1']['EncryptedLmOwfPassword'] = NULL                                                                                                    
                    ╰──────────────────────────────────── [...]

2025-05-03 17:30 UTC, NeffIsBack commented on nxc/modules/change-password.py
> +            netexec smb <DC_IP> -u username -H oldnthash -M change-password -o OLDNTHASH='oldnthash' NEWPASS='newpass'
Makes sense!

2025-05-03 18:47 UTC, KriyosArcane commented on nxc/modules/change-password.py
> +            netexec smb <DC_IP> -u username -H oldnthash -M change-password -o OLDNTHASH='oldnthash' NEWPASS='newpass'
I could remove the options in the help menu but leave as it is right now for any weird specific cases that might occur. Your point is valid though

2025-05-03 21:27 UTC, NeffIsBack commented on nxc/modules/change-password.py
> +            self.context.log.success(f"Successfully changed password for {target_username}")
Fixed the stuff :)

2025-05-03 21:37 UTC, NeffIsBack approved these changes
Added the ability to set an NT hash for the target user (force reset for a different user or yourself):
![image](https://github.com/user-attachments/assets/42f02eb6-7962-4f7b-8cf7-fe6ba4261d2d)

Changing your own Password still works as expected:
![image](https://github.com/user-attachments/assets/550ceb88-9db4-4c55-b8a1-15da30097ef5)


LGTM

2025-05-04 10:06 UTC, merged