Create get_fgpp.py
Pennyw0rth/NetExec pull request #65
Opened 2023-10-10 18:42 UTC by sebrink

Initial script written by n00py, https://github.com/n00py/GetFGPP

Some sample output from my lab:

```
# poetry run NetExec ldap 172.16.14.200 -u user -p password -M get_fgpp          
SMB         172.16.14.200   445    COLOR-DC01       [*] Windows 10.0 Build 14393 x64 (name:COLOR-DC01) (domain:fmradio.local) (signing:True) (SMBv1:False)
LDAP        172.16.14.200   389    COLOR-DC01       [+] fmradio.local\user:password (Pwn3d!)
GET_FGPP    172.16.14.200   389    COLOR-DC01       [+] Attempting to enumerate policies...
GET_FGPP    172.16.14.200   389    COLOR-DC01       2 FGPP Objects found!
GET_FGPP    172.16.14.200   389    COLOR-DC01       
GET_FGPP    172.16.14.200   389    COLOR-DC01       [+] Attempting to enumerate objects with an applied policy...
GET_FGPP    172.16.14.200   389    COLOR-DC01       Object: CN=macheson,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01       Applied Policy: 
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=second policy,CN=Password Settings Container,CN=System,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01       
GET_FGPP    172.16.14.200   389    COLOR-DC01       Object: CN=breakglass01,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01       Applied Policy: 
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=second policy,CN=Password Settings Container,CN=System,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=breakglass-fgpp,CN=Password Settings Container,CN=System,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01       
GET_FGPP    172.16.14.200   389    COLOR-DC01       [+] Attempting to enumerate details...
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Name: breakglass-fgpp
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Length: 24
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password History Length: 
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Threshold: 0
GET_FGPP    172.16.14.200   389    COLOR-DC01       Observation Window: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Duration: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Complexity Enabled: TRUE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Age 1 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Maximum Password Age: 42 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Reversible Encryption: FALSE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Precedence: 1 (Lower is Higher Priority)
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Applies to: 
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=breakglass01,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01       
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Name: second policy
GET_FGPP    172.16.14.200   389    COLOR-DC01       Description: this policy is more of a suggestion tbh
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Length: 0
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password History Length: 
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Threshold: 23
GET_FGPP    172.16.14.200   389    COLOR-DC01       Observation Window: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Duration: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Complexity Enabled: TRUE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Age 1 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Maximum Password Age: 42 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Reversible Encryption: TRUE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Precedence: 2 (Lower is Higher Priority)
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Applies to: 
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=breakglass01,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=macheson,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01   
```

2023-10-10 20:31 UTC, mpgn commented
Hello @sebrink what's the diff with the module PSO ? https://github.com/Pennyw0rth/NetExec/blob/72e42e9b75c9885573eecfc3888252eb93dfba9d/nxc/modules/pso.py

2023-10-10 20:46 UTC, sebrink commented
@mpgn I actually was not aware of the PSO module, so these currently do the exact same thing. There appears to be a bug in the PSO module though that it can't display if there is a policy that applies to multiple objects, see the sample output below: (see the policy titled `second policy`)

get_fgpp:
```
# poetry run NetExec ldap 172.16.14.200 -u username -p password -M get_fgpp
SMB         172.16.14.200   445    COLOR-DC01       [*] Windows 10.0 Build 14393 x64 (name:COLOR-DC01) (domain:fmradio.local) (signing:True) (SMBv1:False)
LDAP        172.16.14.200   389    COLOR-DC01       [+] fmradio.local\rod:yewdall54 (Pwn3d!)
GET_FGPP    172.16.14.200   389    COLOR-DC01       [+] Attempting to enumerate policies...
GET_FGPP    172.16.14.200   389    COLOR-DC01       2 FGPP Objects found!
GET_FGPP    172.16.14.200   389    COLOR-DC01
GET_FGPP    172.16.14.200   389    COLOR-DC01       [+] Attempting to enumerate objects with an applied policy...
GET_FGPP    172.16.14.200   389    COLOR-DC01       Object: CN=macheson,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01       Applied Policy:
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=second policy,CN=Password Settings Container,CN=System,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01
GET_FGPP    172.16.14.200   389    COLOR-DC01       Object: CN=breakglass01,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01       Applied Policy:
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=second policy,CN=Password Settings Container,CN=System,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=breakglass-fgpp,CN=Password Settings Container,CN=System,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01
GET_FGPP    172.16.14.200   389    COLOR-DC01       [+] Attempting to enumerate details...
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Name: breakglass-fgpp
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Length: 15
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password History Length:
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Threshold: 0
GET_FGPP    172.16.14.200   389    COLOR-DC01       Observation Window: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Duration: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Complexity Enabled: TRUE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Age 1 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Maximum Password Age: 42 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Reversible Encryption: FALSE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Precedence: 1 (Lower is Higher Priority)
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Applies to:
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=breakglass01,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Name: second policy
GET_FGPP    172.16.14.200   389    COLOR-DC01       Description: this policy is more of a suggestion tbh
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Length: 7
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password History Length:
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Threshold: 23
GET_FGPP    172.16.14.200   389    COLOR-DC01       Observation Window: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Lockout Duration: 0 days 0 hours 30 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Complexity Enabled: TRUE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Minimum Password Age 1 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Maximum Password Age: 42 days 0 hours 0 minutes 0 seconds
GET_FGPP    172.16.14.200   389    COLOR-DC01       Reversible Encryption: TRUE
GET_FGPP    172.16.14.200   389    COLOR-DC01       Precedence: 2 (Lower is Higher Priority)
GET_FGPP    172.16.14.200   389    COLOR-DC01       Policy Applies to:
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=breakglass01,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01           CN=macheson,CN=Users,DC=fmradio,DC=local
GET_FGPP    172.16.14.200   389    COLOR-DC01
```

pso:
```
# poetry run NetExec ldap 172.16.14.200 -u username -p password -M pso
SMB         172.16.14.200   445    COLOR-DC01       [*] Windows 10.0 Build 14393 x64 (name:COLOR-DC01) (domain:fmradio.local) (signing:True) (SMBv1:False)
LDAP        172.16.14.200   389    COLOR-DC01       [+] fmradio.local\username:password (Pwn3d!)
PSO         172.16.14.200   389    COLOR-DC01       [+] Password Settings Objects (PSO) found:
PSO         172.16.14.200   389    COLOR-DC01       cn: breakglass-fgpp
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordReversibleEncryptionEnabled: FALSE
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordSettingsPrecedence: 1
PSO         172.16.14.200   389    COLOR-DC01       msDS-MinimumPasswordLength: 15
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordHistoryLength: 24
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordComplexityEnabled: TRUE
PSO         172.16.14.200   389    COLOR-DC01       msDS-LockoutObservationWindow: 30 mins
PSO         172.16.14.200   389    COLOR-DC01       msDS-LockoutDuration: 30 mins
PSO         172.16.14.200   389    COLOR-DC01       msDS-LockoutThreshold: 0
PSO         172.16.14.200   389    COLOR-DC01       msDS-MinimumPasswordAge: 1 days
PSO         172.16.14.200   389    COLOR-DC01       msDS-MaximumPasswordAge: 42 days
PSO         172.16.14.200   389    COLOR-DC01       msDS-PSOAppliesTo: CN=breakglass01,CN=Users,DC=fmradio,DC=local
PSO         172.16.14.200   389    COLOR-DC01       -----
PSO         172.16.14.200   389    COLOR-DC01       cn: second policy
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordReversibleEncryptionEnabled: TRUE
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordSettingsPrecedence: 2
PSO         172.16.14.200   389    COLOR-DC01       msDS-MinimumPasswordLength: 7
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordHistoryLength: 0
PSO         172.16.14.200   389    COLOR-DC01       msDS-PasswordComplexityEnabled: TRUE
PSO         172.16.14.200   389    COLOR-DC01       msDS-LockoutObservationWindow: 30 mins
PSO         172.16.14.200   389    COLOR-DC01       msDS-LockoutDuration: 30 mins
PSO         172.16.14.200   389    COLOR-DC01       msDS-LockoutThreshold: 23
PSO         172.16.14.200   389    COLOR-DC01       msDS-MinimumPasswordAge: 1 days
PSO         172.16.14.200   389    COLOR-DC01       msDS-MaximumPasswordAge: 42 days
PSO         172.16.14.200   389    COLOR-DC01       msDS-PSOAppliesTo: CN=breakglass01,CN=Users,DC=fmradio,DC=local
PSO         172.16.14.200   389    COLOR-DC01       -----
```

If you'd like, I can make an update to the PSO module to fix the bug sometime tomorrow or it can potentially be replaced with the get_fgpp module, up to ya'll.

2023-10-10 20:58 UTC, mpgn commented
Your output is better imo

2023-10-10 20:59 UTC, mpgn commented
Maybe name your module pso and delete the old one since bugged anyway

2023-10-10 21:07 UTC, NeffIsBack commented
Agreed, looks better.

@mpgn glad to see you here:)

2023-10-10 21:12 UTC, sebrink commented
Alright it's updated to pso, modified the description and the output to say PSO rather than fgpp. As a note, the original pso module wasn't listed in the e2e_commands.txt.

2023-10-10 22:05 UTC, Marshall-Hallenbeck commented
> Alright it's updated to pso, modified the description and the output to say PSO rather than fgpp. As a note, the original pso module wasn't listed in the e2e_commands.txt.

Thank you for adding it to the e2e tests :)
Could you update the single quotes to double to match our style? Thanks for the PR!

2023-10-10 22:24 UTC, sebrink commented
@Marshall-Hallenbeck done!

2023-10-12 20:34 UTC, Marshall-Hallenbeck commented
Changed to merge into `develop`
@sebrink there's a conflict with the poetry.lock if you can fix that

2023-10-12 21:17 UTC, sebrink commented
Resolved the conflict, looks like running `poetry lock` installs greenlet v3.0.0 rather than greenlet v2.0.2 now using poetry 1.6.1. Happens with the `pyproject.toml` in main right now as well.

2023-10-17 16:14 UTC, sebrink commented
That's almost definitely due to the LDAP query limit of 1000 objects. My lab has less than 1000 so I didn't test for that. I'll put some logic in to catch that. Need to figure out a good way to do it without just capping the module at the first 1000 entries, but nice catch @mpgn !

2023-10-18 19:30 UTC, mpgn commented
Hum looking at the module, if a client has a pso on 7k user, the module will be unreadable

2023-10-19 18:38 UTC, mpgn commented
Going after each object of the domain is overkill, imagine having 20k users

2023-10-19 19:34 UTC, mpgn commented
Fixed the code for you @sebrink 
![image](https://github.com/Pennyw0rth/NetExec/assets/5891788/e347bb08-9804-4b31-bf35-1a639d1c0d44)

2023-10-20 01:30 UTC, Marshall-Hallenbeck requested changes

2023-10-20 01:30 UTC, Marshall-Hallenbeck commented on nxc/modules/pso.py
> +# Toss this in /root/NetExec/nxc/modules
Left over testing comment?

2023-10-20 01:30 UTC, Marshall-Hallenbeck commented on nxc/modules/pso.py
> +        self.__kdcHost = connection.hostname + "." + connection.domain
Use fstrings to concatenate strings here

2023-10-20 01:30 UTC, Marshall-Hallenbeck commented on nxc/modules/pso.py
> +        search_base += "DC=" + b + ","
Use fstring for string concatenation

2023-10-24 18:00 UTC, sebrink commented on nxc/modules/pso.py
> +# Toss this in /root/NetExec/nxc/modules
yep, removed

2023-10-24 18:01 UTC, sebrink commented
Thanks for the fix @mpgn!

2023-10-31 02:34 UTC, Marshall-Hallenbeck commented
@sebrink my big refactor got merged in. Would you mind taking a look at the few conflicts?

2024-03-04 21:11 UTC, mpgn commented
@sebrink any chance to fix the conflict to merge the pr ?

2024-03-16 18:27 UTC, NeffIsBack commented
@mpgn fixed everything, could you give this another review?

2024-03-16 21:30 UTC, mpgn commented
![image](https://github.com/Pennyw0rth/NetExec/assets/5891788/ede11a80-7c9a-4c4b-ab2e-1fcac22f0226)

2024-03-16 21:30 UTC, mpgn approved these changes

2024-03-17 01:26 UTC, NeffIsBack commented
@Marshall-Hallenbeck here are your format strings :)

2024-03-18 18:23 UTC, Marshall-Hallenbeck approved these changes

2024-03-18 18:25 UTC, merged